#!/bin/bash
if [[ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]]
then
 echo This is not supposed to run chrooted
 exit 2
fi
echo "Are you sure to remove FreedomEV?"
echo "This will remove /var/freedomevstart and the crontab entries"
echo "Removing FreedomEV completely"
echo 
echo "Press Enter to continue or ctrl-c to abord"
read
echo Not running chrooted: OK

#check if crontabs are there
alreadyinstalled=$(crontab -l | grep '/var/freedomev')
if [[ "$alreadyinstalled" == "" ]]
then
	echo "No crontab entries found - possibly already removed"
else
	crontab -l | grep -v '/var/freedomev' > /tmp/crontab
	cat /tmp/crontab | crontab
	echo "FreedomEV crontab removal: OK"
fi

if [[ -f /var/freedomevstart ]]
then
	rm /var/freedomevstart && echo "/var/freedomevstart removed" || echo "/var/freedomevstart removal failed"
fi
