#!/bin/bash
app=$1
if [[ ${app} == "" ]]
then
	echo Please provide app name as argument
	exit 3
fi
if [[ $(basename $0) == 'enable-app' ]]
then
	ln -s /freedomev/apps-available/${app} /freedomev/apps/
	/freedomev/apps/${app}/activation
else
	if [ -x /freedomev/apps/${app}/deactivation ]
	then
		/freedomev/apps/${app}/deactivation
	fi
	rm /freedomev/apps/${app} 
fi
